"""Add description field

Revision ID: 9313de1afec6
Revises: c7b4dfc9d835
Create Date: 2026-05-31 22:05:53.990258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9313de1afec6'
down_revision = 'c7b4dfc9d835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
